version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "angularjs"
  ]
  environment = [
    "jest",
    "nodejs",
    "cypress",
    "mocha",
    "jquery"
  ]